---
title: "Supplement 2_Individuals Overnight"
author: "Anusha Shankar"
date: "12/01/2021"
output: word_document
---

```{r setup, echo=F,warning=F}
knitr::opts_chunk$set(fig.width=20, fig.height=8) 
library(ggplot2)
library(stringr)
library(summarytools)

wd <- "C:\\Users\\nushi\\OneDrive - Cornell University\\Shallow_Torpor\\Data\\"
categories <- read.csv(paste0(wd, "Category_thresholds.csv"))
therm_all <- read.csv(paste0(wd, "All_data.csv"))

## Generic plot theme
my_theme <- theme_classic(base_size = 30) + 
  theme(panel.border = element_rect(colour = "black", fill=NA))

my_theme2 <- theme_classic(base_size = 25) + 
  theme(panel.border = element_rect(colour = "black", fill=NA))

## Axis labels
Temp.lab <- expression(atop(paste("Temperature (", degree,"C)")))
STemp.lab <- expression(atop(paste("Surface Temperature (", degree,"C)")))
ATemp.lab <- expression(atop(paste("Ambient Temperature (", degree,"C)")))

## Organizing
therm_all$Category <- factor(therm_all$Category, levels=c("Normothermic", "Shallow Torpor", "Transition", "Deep Torpor"))

## Standardize the color scheme
my_colors <- c("#23988aff", "#F38BA8", "#440558ff", "#9ed93aff")
names(my_colors) <- levels(therm_all$Category)
colScale <- scale_colour_manual(name = "Category", values = my_colors)

##Structuring time
birdTime <- therm_all$Time
TimeOrder1 <- seq(from = 1900, to = 2459, by = 1)
TimeOrder2 <- seq(from = 100, to = 559, by = 1)
TimeOrder <- c(TimeOrder1, paste0("0", TimeOrder2))
TimeOrder <- factor(TimeOrder, as.character(TimeOrder))

birdTime <- as.factor(as.character(str_pad(birdTime, 4, pad = "0")))
therm_all$Time2 <- TimeOrder[match(birdTime,TimeOrder,nomatch=NA)]

therm_doubleCateg <- data.frame()
for(i in unique(therm_all$pasted)) {
    trial <- therm_all[therm_all$pasted==i,]
    trial$Categ2[1] <- as.character(trial$Category[1])
    for(n in 2:length(trial$Category)) {
      trial$Categ2[n] <- as.character(trial$Category[n+1])
      trial$Categ2[length(trial$Category)] <- as.character(trial$Category[length(trial$Category)])
    }
    therm_doubleCateg <- rbind(therm_doubleCateg, trial)
}
therm_doubleCateg$Categ2 <- as.factor(therm_doubleCateg$Categ2)

therm_all$Categ2 <- therm_doubleCateg$Categ2
therm_all$Categ2 <- factor(therm_all$Categ2, levels=c("Normothermic", "Shallow Torpor", "Transition", "Deep Torpor"))
```

```{r eval=FALSE, include=FALSE}
dfSummary(therm_all, plain.ascii = FALSE, style = "grid", 
          graph.magnif = 0.75, valid.col = FALSE)
```

```{r, echo=F, fig.width=20, fig.height=24}
##Plots
# All individuals, faceted by species
# All individuals in one plot
# ggplot(therm_all, aes(Time2, Surf_Temp)) + my_theme2 +
#   facet_grid(Species~.) +
#   geom_line(aes(group=Indiv_numeric, col=Categ2), size=1) +
#   geom_point(aes(col=Category), size=3) +
#   colScale + ylab(Temp.lab) +
#   theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
#         legend.key.height = unit(3, 'lines'), strip.background = element_blank(),
#         strip.text.x = element_blank())
```

```{r echo=F}
## All individuals within a species in one plot per species
func_plots <- function(i){
  ggplot(therm_all[therm_all$Species==i,], aes(Time2, Surf_Temp)) + my_theme2 + facet_grid(.~Species) +
  geom_line(aes(group=Indiv_numeric, col=Categ2), size=1) +
  geom_point(aes(col=Category), size=3) +
  geom_line(aes(group=Indiv_numeric, y=Amb_Temp), linetype="dashed") +
  colScale + ylab(Temp.lab) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.key.height = unit(3, 'lines')) + xlab("Time")
}
lapply(unique(therm_all$Species), func_plots)
```

Just RIHU
```{r echo=F}
## Faceted by individual
ggplot(therm_all[therm_all$Species=="RIHU",], aes(Time2, Surf_Temp)) + my_theme2 +
  facet_wrap(.~Indiv_numeric, scales = "free_x",) + 
  geom_line(aes(group=Indiv_numeric, col=Categ2), size=1) +
  geom_point(aes(col=Category), size=3) +
  #geom_line(aes(group=Indiv_numeric, y=Amb_Temp), linetype="dashed") +
  colScale + ylab(Temp.lab) + xlab("Time of night") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.key.height = unit(3, 'lines'), strip.background = element_blank(),
        strip.text.x = element_blank())
```

Just BLUH
```{r echo=F}
ggplot(therm_all[therm_all$Species=="BLUH",], aes(Time2, Surf_Temp)) + my_theme2 +
  facet_wrap(.~Indiv_numeric, scales = "free_x",) + 
  geom_line(aes(group=Indiv_numeric, col=Categ2), size=1) +
  geom_point(aes(col=Category), size=3) +
  #geom_line(aes(group=Indiv_numeric, y=Amb_Temp), linetype="dashed") +
  colScale + ylab(Temp.lab) + xlab("Time of night") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.key.height = unit(3, 'lines'), strip.background = element_blank(),
        strip.text.x = element_blank())
```

Just BCHU
```{r echo=F}
## Faceted by individual
ggplot(therm_all[therm_all$Species=="BCHU",], aes(Time2, Surf_Temp)) +
  facet_wrap(.~Indiv_numeric, scales = "free_x") + my_theme2 +
  geom_line(aes(group=Indiv_numeric, col=Categ2), size=1) +
  geom_point(aes(col=Category), size=3) +
  #geom_line(aes(group=Indiv_numeric, y=Amb_Temp), linetype="dashed") +
  colScale + ylab(Temp.lab) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.key.height = unit(3, 'lines'), strip.background = element_blank(),
        strip.text.x = element_blank())
```

All individuals, one plot each
```{r echo=F, fig.width=24, fig.height=10}
## Faceted by individual
func_plots <- function(i){
  ggplot(therm_all[therm_all$Indiv_numeric==i,], aes(Time2, Surf_Temp)) + my_theme2 + facet_grid(.~pasted) +
  geom_line(aes(group=Indiv_numeric, col=Categ2), size=1) +
  geom_point(aes(col=Category), size=3) +
  geom_line(aes(group=Indiv_numeric, y=Amb_Temp), linetype="dashed") +
  colScale + ylab(Temp.lab) +
  theme(axis.text.x = element_text(size = 20,  angle=90, hjust=0.5),
        legend.key.height = unit(3, 'lines')) + xlab("Time") +
    scale_x_discrete(guide = guide_axis(n.dodge = 2))
}
lapply(unique(therm_all$Indiv_numeric), func_plots)
```